# Generated by Django 6.0.7 on 2026-07-26 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0001_initial"),
        ("servicios", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mensaje",
            options={"ordering": ["fecha"]},
        ),
        migrations.RemoveField(
            model_name="mensaje",
            name="receptor",
        ),
        migrations.AddField(
            model_name="conversacion",
            name="ultimo_mensaje_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversacion",
            name="ultimo_mensaje_preview",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="editado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conversacion",
            name="estado",
            field=models.CharField(
                choices=[("activa", "Activa"), ("archivada", "Archivada")],
                default="activa",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="conversacion",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversaciones",
                to="servicios.servicio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversacion",
            unique_together={("cliente", "proveedor", "servicio")},
        ),
    ]
