# Generated by Django 6.0.7 on 2026-07-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0002_alter_mensaje_options_remove_mensaje_receptor_and_more"),
        ("servicios", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(
                fields=["cliente", "ultimo_mensaje_fecha"],
                name="conv_cliente_fecha_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(
                fields=["proveedor", "ultimo_mensaje_fecha"],
                name="conv_proveedor_fecha_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mensaje",
            index=models.Index(
                fields=["conversacion", "fecha"], name="msg_conversacion_fecha_idx"
            ),
        ),
    ]
