# Generated by Django 6.0.7 on 2026-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_split_unread_count_by_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo_mensaje',
            field=models.CharField(choices=[('texto', 'Texto'), ('archivo', 'Archivo'), ('ubicacion', 'Ubicación')], default='texto', max_length=20),
        ),
    ]
