# Generated by Django 6.0.7 on 2026-07-27 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mensajeria", "0003_conversacion_conv_cliente_fecha_idx_and_more"),
        ("usuarios", "0003_vistahomecliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloqueo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.CharField(blank=True, default="", max_length=200)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bloqueo",
            },
        ),
        migrations.AddField(
            model_name="conversacion",
            name="unread_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="mensajes/archivos/"
            ),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="estado_entrega",
            field=models.CharField(
                choices=[
                    ("enviado", "Enviado"),
                    ("recibido", "Recibido"),
                    ("leido", "Leído"),
                ],
                default="enviado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="respuestas",
                to="mensajeria.mensaje",
            ),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="tipo_mensaje",
            field=models.CharField(
                choices=[("texto", "Texto"), ("archivo", "Archivo")],
                default="texto",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="mensaje",
            index=models.Index(fields=["deleted_at"], name="msg_deleted_at_idx"),
        ),
        migrations.AddField(
            model_name="bloqueo",
            name="usuario_bloqueado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueos_recibidos",
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="bloqueo",
            name="usuario_bloqueador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueos_realizados",
                to="usuarios.usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="bloqueo",
            index=models.Index(
                fields=["usuario_bloqueador", "usuario_bloqueado"],
                name="bloqueo_bloq_bloq_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bloqueo",
            unique_together={("usuario_bloqueador", "usuario_bloqueado")},
        ),
    ]
