# Generated by Django 6.0.7 on 2026-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0004_mensaje_archivo_nombre_mensaje_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='archivo',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='archivo_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
