# Generated by Django 6.0.7 on 2026-07-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_add_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ('fecha',)},
        ),
    ]
