# Generated by Django 6.0.7 on 2026-07-23 01:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaInfoAplicantes',
            fields=[
                ('id_postulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('servicio_id', models.IntegerField()),
                ('estado_solicitud', models.CharField(max_length=50)),
                ('precio_propuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensaje_proveedor', models.TextField(blank=True, null=True)),
                ('presupuesto_acordado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor_id', models.UUIDField()),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('url_foto_perfil', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('num_reviews', models.IntegerField()),
                ('trabajos_completados', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_info_aplicantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaPostDetails',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagenes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500))),
                ('descripcion', models.TextField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('cliente_id', models.UUIDField()),
                ('url_foto_perfil', models.URLField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('cliente_fecha_registro', models.DateTimeField()),
                ('rating_cliente', models.FloatField()),
                ('num_reviews_cliente', models.IntegerField()),
                ('total_publicaciones_cliente', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_post_details',
                'managed': False,
            },
        ),
    ]
