# Generated by Django 6.0.7 on 2026-07-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_tipocambio_servicio_tipo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to="servicios.tipocambio", db_constraint=False),
        ),
    ]
