# Generated by Django 6.0.7 on 2026-07-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_cleanup_post_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocambio',
            options={'managed': True},
        ),
    ]
