# Generated by Django 6.0.7 on 2026-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_tipocambio_estado_oferta_emisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaConversaciones',
            fields=[
                ('id_conversacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('servicio_id', models.IntegerField()),
                ('servicio_titulo', models.CharField(max_length=150)),
                ('cliente_id', models.UUIDField()),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('foto_cliente', models.URLField(blank=True, null=True)),
                ('proveedor_id', models.UUIDField()),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('foto_proveedor', models.URLField(blank=True, null=True)),
                ('ultimo_mensaje', models.TextField(blank=True, null=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(blank=True, null=True)),
                ('no_leidos_cliente', models.IntegerField()),
                ('no_leidos_proveedor', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_conversaciones',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='postulacion',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
