# Generated by Django 6.0.7 on 2026-08-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_fix_ultimas_publicaciones_cliente'),
        ('servicios', '0005_vistaconversaciones_postulacion_mensaje'),
    ]

    operations = [
    ]
