# Generated by Django 6.0.7 on 2026-08-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_merge_20260805_1421'),
        ('servicios', '0006_merge_20260805_1901'),
    ]

    operations = [
    ]
