# Generated by Django 6.0.7 on 2026-08-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VistaDashboardProveedor',
            fields=[
                ('proveedor_id', models.UUIDField(primary_key=True, serialize=False)),
                ('trabajos_activos', models.IntegerField()),
                ('trabajos_activos_nuevos_semana', models.IntegerField()),
                ('trabajos_activos_nuevos_semana_pasada', models.IntegerField()),
                ('trabajos_activos_pct_cambio', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('trabajos_completados', models.IntegerField()),
                ('completados_semana', models.IntegerField()),
                ('completados_semana_pasada', models.IntegerField()),
                ('completados_pct_cambio', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('ganancias_totales', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ganancias_semana', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ganancias_semana_pasada', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ganancias_pct_cambio', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('promedio_calificacion', models.FloatField()),
                ('num_reviews', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_dashboard_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaPostDetails',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagenes', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('cliente_id', models.UUIDField()),
                ('url_foto_perfil', models.TextField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('cliente_fecha_registro', models.DateTimeField()),
                ('rating_cliente', models.FloatField()),
                ('num_reviews_cliente', models.IntegerField()),
                ('total_publicaciones_cliente', models.IntegerField()),
                ('num_postulantes', models.IntegerField()),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'vista_post_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaTrabajosDisponibles',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('categoria_id', models.IntegerField()),
                ('latitud_aprox', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_aprox', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha', models.DateTimeField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_id', models.IntegerField()),
                ('num_postulantes', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_trabajos_disponibles',
                'managed': False,
            },
        ),
    ]
