# Generated by Django 6.0.7 on 2026-07-20 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('colonia', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=150)),
                ('cp', models.CharField(max_length=10)),
                ('num_int', models.CharField(blank=True, max_length=10, null=True)),
                ('num_ext', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('colonia', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=150)),
                ('cp', models.CharField(max_length=10)),
                ('num_int', models.CharField(blank=True, max_length=10, null=True)),
                ('num_ext', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='usuarios.empresa')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('supabase_uid', models.UUIDField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_pa', models.CharField(max_length=100)),
                ('apellido_ma', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.categoria')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
