# Generated by Django 6.0.7 on 2026-07-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaPerfilCliente',
            fields=[
                ('id_usuario', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('url_foto_perfil', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('num_publicaciones', models.IntegerField()),
                ('rating', models.FloatField()),
                ('num_reviews', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_perfil_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaReviewsCliente',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField()),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('nombre_evaluador', models.CharField(max_length=255)),
                ('foto_evaluador', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_reviews_cliente',
                'managed': False,
            },
        ),
    ]
