# Generated by Django 6.0.7 on 2026-07-26 03:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_vistaperfilcliente_vistareviewscliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaHomeCliente',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha', models.DateTimeField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('estado', models.CharField(max_length=50)),
                ('cliente_id', models.UUIDField()),
                ('fotos_proveedores_aplicantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list)),
            ],
            options={
                'db_table': 'vista_home_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MfaBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'mfa_backup_code',
                'indexes': [models.Index(fields=['usuario', 'code_hash'], name='mfa_backup__id_usua_c095a2_idx')],
            },
        ),
    ]
