# Generated by Django 6.0.7 on 2026-08-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_vistahomecliente_mfabackupcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_area_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaResumenGanancias',
            fields=[
                ('proveedor_id', models.UUIDField(primary_key=True, serialize=False)),
                ('ganancias_esta_semana', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancias_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancias_proyectado', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'vista_resumen_ganancias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaTrabajosAplicados',
            fields=[
                ('id_postulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('proveedor_id', models.UUIDField()),
                ('id_servicio', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('estado_id', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('categoria_id', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'vista_trabajos_aplicados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaTrabajosDisponibles',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('categoria_id', models.IntegerField()),
                ('latitud_aprox', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_aprox', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha', models.DateTimeField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_id', models.IntegerField()),
                ('num_postulantes', models.IntegerField()),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'vista_trabajos_disponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaUltimaResena',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('puntuacion', models.SmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('tiempo_transcurrido', models.DurationField()),
                ('nombre_evaluador', models.CharField(max_length=255)),
                ('foto_evaluador', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
    ]
