# Generated by Django 6.0.7 on 2026-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarioareatrabajo_vistaresumenganancias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('referencia_tabla', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
    ]
