# Generated by Django 6.0.7 on 2026-07-21 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_cliente', to='usuarios.usuario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_proveedor', to='usuarios.usuario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='servicios.servicio')),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
    ]
