# Generated by Django 6.0.7 on 2026-07-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=20, null=True),
        ),
    ]
