# Generated by Django 6.0.7 on 2026-08-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
